#!/bin/sh -l

#PBS -l nodes=1:ppn=24
#PBS -l walltime=0:30:00
#PBS -N pi
#PBS -j oe

cd "$PBS_O_WORKDIR"
export OMP_NUM_THREADS=24

./estimate_pi 100
./estimate_pi 1000
./estimate_pi 10000
./estimate_pi 100000
./estimate_pi 1000000
./estimate_pi 10000000


