#!/bin/sh

# Since we know this is a serial job, ppn=1 will request one core.
# A modest timeout of 5 minutes is requested, since this computation
# is rather simple.

#PBS -l nodes=1:ppn=1
#PBS -l walltime=0:05:00
#PBS -N pi
#PBS -j oe

# Change directories to where this script (and our executable) is.
cd "$PBS_O_WORKDIR"

# Run the computations we want to.
for niter in {100,200,400,800,1600,3200,6400,12800,25600,51200}; do
    ./estimate_pi "$niter"
done
