#!/bin/sh -l

#PBS -l nodes=1:ppn=24
#PBS -l walltime=0:30:00
#PBS -N pi
#PBS -j oe

cd "$PBS_O_WORKDIR"
./estimate_pi 100
./estimate_pi 200
./estimate_pi 400
./estimate_pi 800
./estimate_pi 1600
./estimate_pi 3200
./estimate_pi 6400
./estimate_pi 12800
./estimate_pi 25600
./estimate_pi 51200
